# Generated by Django 4.1.2 on 2022-10-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Марка')),
                ('thing', models.CharField(max_length=120, verbose_name='Какая')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
