# Generated by Django 4.1.2 on 2022-10-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_orders_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
